build: false

environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python35"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  # FIXME: updating pip fails with PermissionError
  # - "%PYTHON%/Scripts/pip.exe install -U pip setuptools"
  - "%PYTHON%/Scripts/pip.exe install -e ."

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/python.exe setup.py test"
